BC House ASP/Controllers/KlantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BC_House_ASP.Container;
using BC_House_ASP.Database;
using BC_House_ASP.Interface;
using BC_House_ASP.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BC_House_ASP.Controllers
{
    public class KlantController : Controller
    {
        KlantContainer klantContainer;

        public KlantController()
        {
            klantContainer = new KlantContainer(new KlantDAL());
        }

        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Home()
        {
            return View("../Home/Index");
        }
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Klant klant)
        {
            if (klant.klantEmail == null)
            {
                return View("Login");
            }
            else if (klant.klantPassword == null)
            {
                return View("Login");
            }
            else if (klantContainer.CheckIfUserExists(klant))
            {
                Klant currentKlant = new Klant();

                currentKlant = klantContainer.LoginKlant(klant);
              
                HttpContext.Session.SetString("Id", currentKlant.Id.ToString());
                HttpContext.Session.SetString("klantNaam", currentKlant.klantNaam);
                HttpContext.Session.SetString("klantEmail", currentKlant.klantEmail);
                HttpContext.Session.SetString("telefoonNummer", currentKlant.telefoonNummer);
                HttpContext.Session.SetString("straat", currentKlant.straat);
                HttpContext.Session.SetString("huisNummer", currentKlant.huisNummer);
                HttpContext.Session.SetString("woonplaats", currentKlant.woonplaats);
                HttpContext.Session.SetString("postcode", currentKlant.postcode);

                //Go to homepage
                return RedirectToAction("Home", currentKlant);
            }
            else
            {
                ////Show wrong password error
                ModelState.AddModelError("klantEmail", "Fout wachtwoord of email.");
                return View("Login");
            }
        }
        [HttpPost]
        public ActionResult Register(Klant klant)
        {
            if (klant.klantNaam == null || klant.klantEmail == null || klant.telefoonNummer == null || klant.klantPassword == null || 
                klant.postcode == null || klant.huisNummer == null || klant.straat == null || klant.woonplaats == null)
            {
                ModelState.AddModelError("klantEmail", "Vul alle gegevens in!");
                return View("Register");
            }
            else if (klantContainer.registerCheck(klant))
            {
                klantContainer.Accountmaken(klant);
                return RedirectToAction("Login");
            }
            else
            {
                ////Show wrong password error
                ModelState.AddModelError("klantEmail", "Vul geldige gegevens in!.");
                return View("Register");
            }
        }

        public ActionResult Logout()
        {
            //HttpContext.Session.Clear();

            return RedirectToAction("Login");
        }
    }
}

BC House ASP/Controllers/WinkelwagenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BC_House_ASP.Container;
using BC_House_ASP.Database;
using BC_House_ASP.Models;
using Microsoft.AspNetCore.Mvc;

namespace BC_House_ASP.Controllers
{
    public class WinkelwagenController : Controller
    {
        WinkelwagenContainer winkelwagenContainer;

        public WinkelwagenController()
        {
            winkelwagenContainer = new WinkelwagenContainer(new WinkelwagenDAL());
        }

        public IActionResult Winkelwagen()
        {
            return View();
        }

        [HttpGet]
        public ActionResult WinkelwagenOverzicht()
        {
            List<Winkelwagen> productslist = winkelwagenContainer.GetList();
            return PartialView("../Partials/_WinkelwagenList", productslist);
        }

        [HttpPost]
        // Producten toevoegen aan winkelwagen
        public void AddToCard (int productID, int Quantity)
        {
            Product product = new Product();
            Winkelwagen winkelwagen = new Winkelwagen(product.id);
            winkelwagen.Prod.id = productID;
            winkelwagen.hoeveelheid = Quantity;

            SetQuantity(product, winkelwagen);
            winkelwagenContainer.AddProductToCart(product, winkelwagen);
        }

        public void SetQuantity(Product productID, Winkelwagen Quantity)
        {
            winkelwagenContainer.SetProductQuantity(productID, Quantity);
        }

        [HttpPost]
        public void ProductRemove(int productID)
        {
            Product product = new Product();
            Winkelwagen winkelwagen = new Winkelwagen(product.id);
            winkelwagen.Prod.id = productID;
            winkelwagenContainer.RemoveProduct(winkelwagen);
        }
    }
}

BC House ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Burger & Chicken House</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <!-- Navbar-->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white mb-3">
            <div class="container">
                <!-- Brand/logo -->
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo2.png" alt="logo" style="width:350px;">
                </a>

                <!-- Links -->
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Winkelwagen" asp-action="Winkelwagen">Winkelwagen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Mijn account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Klant" asp-action="Logout">Uitloggen</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="footer">
        <div class="container">
            &copy; 2020 - Burger & Chicken House
        </div>
    </footer>

    <!--Sweetalert-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>